apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  type: LoadBalancer
  ports:
    - port: 80
      containerPort: 8000
  selector:
    app: edgemicro
