apiVersion: v1
kind: Service
metadata:
  name: inbound
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30303
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: outbound
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway   # matches host name used for gateway service in nginx config
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 10010
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: target2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 10011
  selector:
    app: gateway
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: nginx
        image: 192.168.64.1:5000/ngixsandwich_nginx
        ports:
        - containerPort: 8080 # inbound
        - containerPort: 8081 # outbound
      - name: micro-gateway
        image: 192.168.64.1:5000/ngixsandwich_gateway
        ports:
        - containerPort: 10010
        env:
        - name: outbound                 # used by gateway as outgoing host
          value: http://outbound
      - name: target
        image: 192.168.64.1:5000/nginxsandwich_target1
        ports:
        - containerPort: 10011
        env:
        - name: PORT
          value: '10011'

#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: nginx-ingress
#spec:
#  backend:
#    serviceName: inbound
#    servicePort: 80

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: target2
#spec:
#  type: ClusterIP
#  ports:
#    - port: 80
#      targetPort: 10011
#  selector:
#    app: target-po
#---
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: target-po
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: target-po
#    spec:
#      containers:
#      - name: target
#        image: scottganyo/nginx-sandwich-target
#        ports:
#        - containerPort: 10010
